permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]
 # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


# 作者信息
author: 
  name: Fan Yuanping
  email: fanapplefan@gmail.com
  link: http://asfan.github.io
  weibo: http://weibo.com/fanapplefan
  github: http://github.com/asfan
#  music: http://site.douban.com/linanya
#  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: asfan的blog
description: Personal blog of asfan
url: http://asfan.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/asfan.jpg
favicon: /public/img/asfan.jpg

# ga 设置 目前还没有玩起来（可以对自己的blog做个分析，可以试着做soa啦 哈哈哈）
#ga:
#  id: UA-54262064-1 
#  url: painterlin.com

# disqus 设置
disqus:
#  shortname: painterlin
  shortname: asfan

# 主题设置，自动激活某个标签
active: Language

# 首页除了最新文章外显示category分类
cates_index: 
  - 设计模式
  - REDIS
  - 随笔

# 左导的排序
cates_list:
  - LNMP
  - 设计模式
  - 架构
  - 语言
  - 学习中
  - REDIS
  - 基础知识
  - 管理
  - 阅读
  - 随笔

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

#gems
gems: [jekyll-paginate]

